FROM golang:1.21.1

WORKDIR /app

ENV PATH="/go/bin:${PATH}"

COPY . .

RUN go mod tidy

RUN apt-get update && apt-get install sqlite3 -y

# RUN usermod -u 1000 www-data
# RUN mkdir -p /var/www/.cache
# RUN chown -R www-data:www-data /app
# RUN chown -R www-data:www-data /var/www/.cache
# USER www-data

CMD ["tail", "-f", "/dev/null"]